- name: Play Level variables
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
    - name: Print Play variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: File Level Variables
  hosts: localhost
  ## vars_files works only on play level. on Task level we cannot access these files
  vars_files:
    - vars.yml
  tasks:
    - name: Print play variable from file
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: Task level Variables
  hosts: localhost
  tasks:
    - name: Print Task level Variables
      vars: ## These variables are accessed only in this task, next task on same play cannot access
          URL: task.example.com
      ansible.builtin.debug:
          msg: URL = {{ URL }}

- name: Inventory Level Variables
  hosts: all
  tasks:
    - name: Print Inventory level Variables
      ansible.builtin.debug:
        msg: URL = {{ URL }}, Hostname of server = {{ ansible_hostname }}

- name:  Register a Variable
  hosts: localhost
  tasks:
    - name: Get uptime
       ansible.builtin.shell:uptime
        register:out
    - name: print output
      ansible.builtin.debug:
          msg: "{{ out }}"

