- name: Play variables
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
    - name: Print Play Variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: Play variables from file
  hosts: localhost
  var_files:
    - vars.yml
  tasks:
    - name: Print play variable from file
      ansible.builtin.debug:
        msg: URL = {{ URL }}
